// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvzqrzlklxnfmpwwwksc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2enFyemxrbHhuZm1wd3d3a3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDU4MDUsImV4cCI6MjA3MjAyMTgwNX0.Q7zUSJvsJycWIpJKn8JvnsQiNz2jFZ3oPi6Ukpuh8C4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});